# Generated by Django 5.1.1 on 2024-09-21 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Apointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(null=True)),
                ('appointment_name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=100)),
                ('transaction_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=255)),
                ('college_initials', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commend', models.CharField(max_length=100)),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('status', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('smc_email', models.EmailField(max_length=255)),
                ('smc_id_no', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('smc_student_no', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=255)),
                ('smc_email', models.EmailField(max_length=255)),
                ('receipt_no', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=255)),
                ('account_typeid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EthicsApp.account_type')),
                ('college_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EthicsApp.college')),
                ('reviewer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EthicsApp.reviewer')),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EthicsApp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Manuscripts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thesis_title', models.CharField(max_length=255)),
                ('thesis_description', models.CharField(max_length=255)),
                ('category_name', models.CharField(max_length=255)),
                ('type_of_study', models.CharField(max_length=700)),
                ('study_site', models.CharField(max_length=255)),
                ('no_studyparticipants', models.CharField(max_length=255)),
                ('file', models.URLField(verbose_name='File Url')),
                ('account_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EthicsApp.accounts')),
            ],
        ),
    ]
