# Generated by Django 5.1.1 on 2024-09-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EthicsApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='date',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='time',
        ),
        migrations.AddField(
            model_name='schedule',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='schedname',
            field=models.CharField(default='Unnamed Schedule', max_length=120),
        ),
        migrations.AlterField(
            model_name='manuscripts',
            name='thesis_description',
            field=models.TextField(null=True),
        ),
    ]
