# Generated by Django 5.1.1 on 2024-10-02 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EthicsApp', '0002_remove_schedule_date_remove_schedule_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='smc_email',
        ),
    ]
