# Generated by Django 5.1.1 on 2024-09-21 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EthicsApp', '0002_events_remove_schedule_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
