# Generated by Django 5.1.1 on 2024-10-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EthicsApp', '0005_remove_schedule_datetime_remove_schedule_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='schedule_end_time',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_start_time',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
