# Generated by Django 5.1.1 on 2024-10-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EthicsApp', '0008_remove_reviewer_first_name_remove_reviewer_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='invite_status',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
