# Generated by Django 5.1.1 on 2024-10-25 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EthicsApp', '0009_accounts_invite_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='account_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EthicsApp.accounts'),
        ),
    ]
