# Generated by Django 5.1.1 on 2024-11-27 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EthicsApp', '0013_thesistype_student_receipt_no2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='ethicalAnswers_id',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='ethicalriskanswers',
            name='student_id',
        ),
        migrations.AddField(
            model_name='appointments',
            name='account_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EthicsApp.accounts'),
        ),
        migrations.AddField(
            model_name='ethicalriskanswers',
            name='appointment_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EthicsApp.appointments'),
        ),
    ]
