# Generated by Django 5.1.1 on 2025-01-14 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EthicsApp', '0015_schedule_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuscripts',
            name='category_name_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EthicsApp.category'),
        ),
        migrations.AlterField(
            model_name='manuscripts',
            name='type_of_study_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EthicsApp.typeofstudy'),
        ),
    ]
