# Generated by Django 5.1.4 on 2025-01-14 08:23

import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EthicsApp', '0015_schedule_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manuscripts',
            name='category_name_id',
        ),
        migrations.RemoveField(
            model_name='manuscripts',
            name='no_studyparticipants',
        ),
        migrations.RemoveField(
            model_name='manuscripts',
            name='type_of_study_id',
        ),
        migrations.AddField(
            model_name='manuscripts',
            name='category_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EthicsApp.category'),
        ),
        migrations.AddField(
            model_name='manuscripts',
            name='type_of_study',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EthicsApp.typeofstudy'),
        ),
        migrations.AlterField(
            model_name='manuscripts',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(), upload_to='manuscripts/'),
        ),
    ]
