# Generated by Django 5.1.4 on 2025-01-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EthicsApp', '0016_remove_manuscripts_category_name_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='address_of_institution',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
