# Generated by Django 5.1.4 on 2025-01-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EthicsApp', '0017_appointments_address_of_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='duration_end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='appointments',
            name='duration_start_time',
            field=models.TimeField(null=True),
        ),
    ]
