# Generated by Django 5.1.4 on 2025-01-14 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EthicsApp', '0018_appointments_duration_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='duration_end_time',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='duration_start_time',
            field=models.DateField(null=True),
        ),
    ]
