# Generated by Django 5.1.4 on 2025-01-14 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EthicsApp', '0020_appointments_basicrequirements_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='account_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EthicsApp.account_type'),
        ),
    ]
