# Generated by Django 5.1.4 on 2025-01-15 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EthicsApp', '0021_alter_schedule_account_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='account_typeid',
            new_name='account_id',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='account_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EthicsApp.accounts'),
        ),
    ]
