# Generated by Django 5.1.4 on 2025-01-15 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EthicsApp', '0022_rename_account_typeid_accounts_account_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='account_id',
            new_name='account_type',
        ),
    ]
