# Generated by Django 5.1.4 on 2025-01-15 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EthicsApp', '0024_rename_account_type_accounts_account_typeid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimStabs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeOfReview', models.CharField(max_length=255, null=True)),
                ('releaseDate', models.DateField(null=True)),
                ('received_by', models.CharField(max_length=800, null=True)),
                ('appointment_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EthicsApp.appointments')),
            ],
        ),
    ]
