# Generated by Django 5.1.1 on 2025-01-16 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EthicsApp', '0016_alter_manuscripts_category_name_id_and_more'),
        ('EthicsApp', '0025_claimstabs'),
    ]

    operations = [
    ]
